{{
    config
    (
        materialized='table'
    ) 
}}

with cms_provider as
(
    select
        CMS_CERTIFICATION_NUMBER
        ,PROVIDER_NAME
        ,PROVIDER_ADDRESS
        ,CITY
        ,STATE
        ,ZIP_CODE
        ,TELEPHONE_NUMBER
        ,PROVIDER_SSA_COUNTY_CODE
        ,COUNTY
        ,URBAN
        ,OWNERSHIP_TYPE
        ,NUMBER_OF_CERTIFIED_BEDS
        ,AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY
        ,AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY_FOOTNOTE
        ,PROVIDER_TYPE
        ,PROVIDER_RESIDES_IN_HOSPITAL
        ,LEGAL_BUSINESS_NAME
        ,CHAIN_NAME
        ,CHAIN_ID
        ,NUMBER_OF_FACILITIES_IN_CHAIN
        ,CHAIN_AVERAGE_OVERALL_5STAR_RATING
        ,CHAIN_AVERAGE_HEALTH_INSPECTION_RATING
        ,CHAIN_AVERAGE_STAFFING_RATING
        ,CHAIN_AVERAGE_QM_RATING
        ,OVERALL_RATING
        ,HEALTH_INSPECTION_RATING
        ,QM_RATING
        ,LONG_STAY_QM_RATING
        ,SHORT_STAY_QM_RATING
        ,STAFFING_RATING
        ,REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY
        ,REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY
        ,REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY
        ,REPORTED_LICENSED_STAFFING_HOURS_PER_RESIDENT_PER_DAY
        ,REGISTERED_NURSE_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND
        ,REPORTED_PHYSICAL_THERAPIST_STAFFING_HOURS_PER_RESIDENT_PER_DAY
        ,TOTAL_NURSING_STAFF_TURNOVER
        ,REGISTERED_NURSE_TURNOVER
        ,NUMBER_OF_ADMINISTRATORS_WHO_HAVE_LEFT_THE_NURSING_HOME
    from {{source('cms_provider', 'PROVIDER_INFO_DEC2025')}}
)

SELECT * FROM cms_provider