WITH AVG_HOURS AS
(
SELECT
    STATE,
    ROUND(AVG(REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY), 2) AS AVG_NURSE_AIDE_HOURS,
    ROUND((SELECT AVG(REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY) FROM provider_info_dec2025 WHERE staffing_rating IS NOT NULL), 2) as NATIONAL_AVG_NURSE_AIDE_HOURS,
    ROUND(AVG(REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY), 2) AS AVG_LPN_HOURS,
    ROUND((SELECT AVG(REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY) FROM provider_info_dec2025 WHERE staffing_rating IS NOT NULL), 2) as NATIONAL_AVG_LPN_HOURS,
    ROUND(AVG(REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY), 2) AS AVG_RN_HOURS,
    ROUND((SELECT AVG(REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY) FROM provider_info_dec2025 WHERE staffing_rating IS NOT NULL), 2) as NATIONAL_AVG_RN_HOURS
FROM 
    STAFFING_STATS_BASE
GROUP BY
    STATE
ORDER BY
    STATE ASC
),

RANK_STATS AS
(
SELECT
    A.STATE,
    B.FULL_STATE,
    ROUND(((AVG_NURSE_AIDE_HOURS/NATIONAL_AVG_NURSE_AIDE_HOURS)*100)) AS NURSE_AIDE_STAFFING_LEVEL,
    ROUND(((AVG_NURSE_AIDE_HOURS/NATIONAL_AVG_NURSE_AIDE_HOURS)*100)) AS LPN_STAFFING_LEVEL,
    ROUND(((AVG_NURSE_AIDE_HOURS/NATIONAL_AVG_NURSE_AIDE_HOURS)*100)) AS RN_STAFFING_LEVEL,
    B.TOTAL_PROVIDERS_BY_STATE AS TOTAL_PROVIDERS_BY_STATE,
    SUM(B.TOTAL_PROVIDERS_BY_STATE) OVER() AS NATIONAL_PROVIDER_TOTAL,
    RANK() OVER(ORDER BY B.TOTAL_PROVIDERS_BY_STATE DESC) AS MARKET_SIZE_RANK
FROM
    AVG_HOURS AS A
INNER JOIN
    STATE_STAFFING_COUNT AS B ON A.STATE = B.STATE
ORDER BY
    TOTAL_PROVIDERS_BY_STATE DESC
)

SELECT 
    *,
    TOTAL_PROVIDERS_BY_STATE/NATIONAL_PROVIDER_TOTAL AS PERCENTAGE_OF_TOTAL
FROM 
    RANK_STATS